# Generated by Django 4.2.30 on 2026-05-05 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=20)),
                ('min_score', models.FloatField()),
                ('max_score', models.FloatField()),
                ('color_hex', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='ProsCons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pro', models.BooleanField()),
                ('category', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('source', models.CharField(default='MANUAL', max_length=20)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pros_cons', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='MLScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('overall_score', models.FloatField()),
                ('profitability_score', models.FloatField()),
                ('growth_score', models.FloatField()),
                ('leverage_score', models.FloatField()),
                ('cashflow_score', models.FloatField()),
                ('dividend_score', models.FloatField()),
                ('trend_score', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_scores', to='companies.company')),
                ('health_label', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.healthlabel')),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(max_length=20)),
                ('compounded_sales_growth_pct', models.FloatField(blank=True, null=True)),
                ('compounded_profit_growth_pct', models.FloatField(blank=True, null=True)),
                ('stock_price_cagr_pct', models.FloatField(blank=True, null=True)),
                ('roe_pct', models.FloatField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='companies.company')),
            ],
            options={
                'verbose_name_plural': 'Analysis',
            },
        ),
    ]
