# Generated by Django 4.2.30 on 2026-05-05 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitLoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('operating_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('opm_pct', models.FloatField(blank=True, null=True)),
                ('other_income', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('interest', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('depreciation', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('profit_before_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('tax_pct', models.FloatField(blank=True, null=True)),
                ('net_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('eps', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dividend_payout_pct', models.FloatField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_loss', to='companies.company')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.fiscalyear')),
            ],
            options={
                'unique_together': {('company', 'year')},
            },
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_activity', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('investing_activity', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('financing_activity', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('net_cash_flow', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('free_cash_flow', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flows', to='companies.company')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.fiscalyear')),
            ],
            options={
                'unique_together': {('company', 'year')},
            },
        ),
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equity_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('reserves', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('borrowings', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('other_liabilities', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_liabilities', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('fixed_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('cwip', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('investments', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('other_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('debt_to_equity', models.FloatField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_sheets', to='companies.company')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.fiscalyear')),
            ],
            options={
                'unique_together': {('company', 'year')},
            },
        ),
    ]
