# Generated by Django 4.2.30 on 2026-05-05 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_label', models.CharField(max_length=20, unique=True)),
                ('fiscal_year', models.IntegerField()),
                ('quarter', models.CharField(blank=True, max_length=5, null=True)),
                ('is_ttm', models.BooleanField(default=False)),
                ('is_half_year', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(max_length=100, unique=True)),
                ('sector_code', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('symbol', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('sub_sector', models.CharField(blank=True, max_length=100, null=True)),
                ('company_logo', models.URLField(blank=True, max_length=500, null=True)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('nse_url', models.URLField(blank=True, max_length=500, null=True)),
                ('bse_url', models.URLField(blank=True, max_length=500, null=True)),
                ('face_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('book_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('about_company', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='companies.sector')),
            ],
        ),
    ]
